version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./notification_service/Dockerfile
    container_name: notification_api
    image: notification-api-image
    env_file:
      - ./.env
    expose:
      - "8000"
    command: bash entrypoint-api.sh
    volumes:
      - ./notification_service/src:/app/src
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: notification_nginx
    restart: always
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx/sites:/etc/nginx/conf.d:ro
      - ./configs/nginx/auth:/etc/nginx/auth:ro
    ports:
      - "80:80"
    depends_on:
      - api

  db:
    image: postgres:16
    container_name: notification_db
    restart: always
    volumes:
      - notification_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${NOTIFY_POSTGRES_PASSWORD}
      - POSTGRES_DB=${NOTIFY_POSTGRES_NAME}
    ports:
      - 5436:5432
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ${NOTIFY_POSTGRES_NAME}" ]
      interval: 5s
      retries: 5
      timeout: 5s

  redis:
    image: redis:7.4.1-alpine
    container_name: notification_redis
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  rabbitmq:
    image: rabbitmq:4.0.5-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env
    environment:
      RABBITMQ_DEFAULT_USER: ${NOTIFY_RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${NOTIFY_RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  worker-defaults: &worker-defaults
    build:
      context: .
      dockerfile: ./notification_service/Dockerfile
    image: notification-api-image
    env_file:
      - ./.env
    volumes:
      - ./notification_service/src:/app/src
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker-former-low:
    <<: *worker-defaults
    container_name: notification_worker_former_low
    command: uv run workers/former/former_worker.py notifications.low

  worker-former-medium:
    <<: *worker-defaults
    container_name: notification_worker_former_medium
    command: uv run workers/former/former_worker.py notifications.medium

  worker-former-high:
    <<: *worker-defaults
    container_name: notification_worker_former_high
    command: uv run workers/former/former_worker.py notifications.high

  worker-repeater:
    <<: *worker-defaults
    container_name: notification_worker_repeater
    command: bash entrypoint-worker.sh repeater
  
  worker-scheduler:
    <<: *worker-defaults
    container_name: notification_worker_scheduler
    command: bash entrypoint-worker.sh scheduler

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  api-test:
    build:
      context: .
      dockerfile: ./notification_service/Dockerfile.test
    container_name: notification_api_test
    image: notification-api-image
    env_file:
      - ./.env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

volumes:
  notification_data:
  rabbitmq_data:
