"""Initial

Revision ID: 7d35a64c4c58
Revises: 
Create Date: 2025-02-14 19:07:29.842966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d35a64c4c58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('periodicnotification',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.Enum('EMAIL', 'SMS', 'PUSH', name='channeltype'), nullable=False),
    sa.Column('event_type', sa.Enum('USER_REGISTRATION', 'NEW_MOVIE', 'CUSTOM', name='eventtype'), nullable=False),
    sa.Column('cron_schedule', sa.String(length=100), nullable=False),
    sa.Column('last_run_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('stop_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscriber_query_type', sa.String(length=50), nullable=False),
    sa.Column('subscriber_query_params', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_periodic_notifications_active_next_run', 'periodicnotification', ['is_active', 'next_run_time'], unique=False, postgresql_where=sa.text('is_active IS true'))
    op.create_index('ix_periodic_notifications_user', 'periodicnotification', ['subscriber_query_type'], unique=False)
    op.create_table('schedulednotification',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.Enum('EMAIL', 'SMS', 'PUSH', name='channeltype'), nullable=False),
    sa.Column('event_type', sa.Enum('USER_REGISTRATION', 'NEW_MOVIE', 'CUSTOM', name='eventtype'), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('subscriber_query_type', sa.String(length=50), nullable=False),
    sa.Column('subscriber_query_params', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_scheduled_notifications_pending', 'schedulednotification', ['is_sent', 'scheduled_time'], unique=False, postgresql_where=sa.text('is_sent IS false'))
    op.create_index('ix_scheduled_notifications_query_type', 'schedulednotification', ['subscriber_query_type', sa.text('scheduled_time DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_notifications_query_type', table_name='schedulednotification')
    op.drop_index('ix_scheduled_notifications_pending', table_name='schedulednotification', postgresql_where=sa.text('is_sent IS false'))
    op.drop_table('schedulednotification')
    op.drop_index('ix_periodic_notifications_user', table_name='periodicnotification')
    op.drop_index('ix_periodic_notifications_active_next_run', table_name='periodicnotification', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('periodicnotification')
    op.drop_table('template')
    # ### end Alembic commands ###
